GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2V2aW4iLCJpYXQiOjE2MDU4NDQxMTd9.82i1vPBsNbRc9q9Hsh-RgGR8JzcaHnvAz48zI32rkgc


###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "refreshToken"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}


###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "refreshToken"
}